/*
 * YuviLearn — the learning bridge every generated game talks to.
 * Injected at serve time (never generated by the model).
 *
 * Two modes, chosen by the injector:
 *   - "parent": the game runs inside the Yuvi app iframe; answers are graded by
 *     the parent (server-side) via postMessage. No answer key in the page.
 *   - "local": headless validation / preview; an answer key is injected as
 *     window.__YUVI_LEARN_KEY and graded here. Never used for served games.
 *
 * API (all return Promises):
 *   YuviLearn.next()                 -> {id, text, answers:[...], index, total} | null when exhausted
 *   YuviLearn.answer(id, answer)     -> {correct:boolean, correctAnswer?:string, feedback?:string}
 *   YuviLearn.progress()             -> {asked, answered, correct, total}
 *   YuviLearn.done(summary?)         -> void   (game finished; parent may show the celebration)
 *   YuviLearn.reset()                -> void   (start the question cycle again)
 * Sync helpers: YuviLearn.total, YuviLearn.language, YuviLearn.componentTitle
 */
(function () {
  if (window.YuviLearn) return;
  var data = window.__YUVI_LEARN_DATA || { questions: [], language: 'he', component: {} };
  var key = window.__YUVI_LEARN_KEY || null; // local mode only
  var mode = key ? 'local' : (window.parent && window.parent !== window ? 'parent' : 'local');
  var nonce = window.__YUVI_NONCE || '';
  var state = (window.__yuvi = window.__yuvi || {});
  state.learn = state.learn || { asked: 0, answered: 0, correct: 0, done: false };
  state.learn.total = data.questions.length;
  state.heartbeat = state.heartbeat || 0;
  state.errors = state.errors || [];

  var cursor = 0;
  var pending = {};
  var seq = 0;

  function norm(s) {
    return String(s == null ? '' : s).replace(/\s+/g, ' ').trim().toLowerCase();
  }
  function findQuestion(id) {
    for (var i = 0; i < data.questions.length; i++) if (data.questions[i].id === id) return data.questions[i];
    return null;
  }
  function resolveAnswerText(q, answer) {
    if (typeof answer === 'number' && q && q.answers && q.answers[answer] != null) return q.answers[answer];
    return answer;
  }
  function gradeLocal(id, answer) {
    var q = findQuestion(id);
    var text = norm(resolveAnswerText(q, answer));
    var accepted = (key && key[id]) || [];
    var correct = false;
    for (var i = 0; i < accepted.length; i++) if (norm(accepted[i]) === text) correct = true;
    return { correct: correct, correctAnswer: correct ? undefined : accepted[0] };
  }
  function post(type, payload) {
    try { window.parent.postMessage(Object.assign({ source: 'yuvi-game', type: type, nonce: nonce }, payload), '*'); } catch (e) {}
  }
  if (mode === 'parent') {
    window.addEventListener('message', function (ev) {
      var m = ev && ev.data;
      if (!m || m.source !== 'yuvi-host' || m.type !== 'learn.answer.result') return;
      var p = pending[m.requestId];
      if (!p) return;
      delete pending[m.requestId];
      p.resolve({ correct: !!m.correct, correctAnswer: m.correctAnswer, feedback: m.feedback });
    });
  }

  window.YuviLearn = {
    get total() { return data.questions.length; },
    get language() { return data.language || 'he'; },
    get componentTitle() { return (data.component && data.component.title) || ''; },
    next: function () {
      if (cursor >= data.questions.length) return Promise.resolve(null);
      var q = data.questions[cursor];
      var out = { id: q.id, text: q.text, answers: (q.answers || []).slice(), type: q.type, index: cursor, total: data.questions.length };
      cursor += 1;
      state.learn.asked += 1;
      post('learn.asked', { questionId: q.id, index: out.index });
      return Promise.resolve(out);
    },
    answer: function (id, answer) {
      state.learn.answered += 1;
      var finish = function (r) {
        if (r && r.correct) state.learn.correct += 1;
        post('learn.answered', { questionId: id, correct: !!(r && r.correct) });
        return r;
      };
      if (mode === 'local') return Promise.resolve(finish(gradeLocal(id, answer)));
      var requestId = 'a' + (++seq);
      var q = findQuestion(id);
      return new Promise(function (resolve) {
        pending[requestId] = { resolve: function (r) { resolve(finish(r)); } };
        post('learn.answer', { requestId: requestId, questionId: id, answer: resolveAnswerText(q, answer) });
        setTimeout(function () {
          if (pending[requestId]) { delete pending[requestId]; resolve(finish({ correct: false, feedback: 'timeout' })); }
        }, 8000);
      });
    },
    progress: function () {
      return Promise.resolve({ asked: state.learn.asked, answered: state.learn.answered, correct: state.learn.correct, total: data.questions.length });
    },
    done: function (summary) {
      state.learn.done = true;
      post('learn.done', { summary: summary || null, progress: { asked: state.learn.asked, answered: state.learn.answered, correct: state.learn.correct } });
      return Promise.resolve();
    },
    reset: function () { cursor = 0; return Promise.resolve(); }
  };
  post('ready', { mode: mode, total: data.questions.length });
})();
