"""The content-intelligence contract: one module both sides import.

The nightly pipeline (``scripts/content_pipeline.py``) writes a repo-committed
config — ``content/context/<subject>/<objective>.json`` — of per-slide content
metadata and pre-generated Hebrew texts. The coach reads it at runtime to serve
those texts instead of regenerating them per learner, and to ground free-text
answers in what the slide actually shows. Everything the two sides must agree
on lives HERE — schema version, fingerprint functions, key shapes, the
correct-answers ban — so the contract cannot drift: there is no spec document,
there is this module.

## Freshness is the whole safety story

A pre-generated text is served only while the authored content it was written
from is byte-identical to what the live catalog says right now
(``source_fingerprint`` matches a fingerprint recomputed from the same shared
functions) AND it was generated by the current prompt (``prompt_version``).
Any mismatch, any missing record, any load failure → the caller falls through
to live generation, which is exactly today's behavior. The config can make the
coach faster; it can never make it staler than the catalog snapshot the live
path would have read anyway.

## correctAnswers never enter the repo

The config file is world-readable to anyone with the git URL, students
included. ``correctAnswers`` stay where they live today — the live catalog,
server-side only. The serializer refuses to write a shard containing one, and
the loader discards an entire file that smuggles one in (a poisoned file must
not half-work). No hashes of answers either: with four visible options a
digest is brute-forceable, and ``question_topics`` already set the rule — the
hash must never travel near the key.
"""

from __future__ import annotations

import hashlib
import json
import os
from pathlib import Path
from typing import Any, Iterable, Optional

SCHEMA_VERSION = 1

#: Stamped into every generated text. Bump a kind's entry in PROMPT_VERSIONS
#: when ITS generation prompt changes in a way that makes previously stored
#: texts wrong — that kind goes stale at once and the next nightly run
#: regenerates it, while the other kinds keep their texts (question_topics
#: precedent, refined per kind). PROMPT_VERSION stays the default for kinds
#: whose prompt never changed.
# cp-v2 (2026-08-31): intros became openers — orient and invite, never
# paraphrase the question/screen or foreshadow the answer (the balloon-intro
# feedback) — and every kind may now use light markdown emphasis, matching
# what the live coach writes and what the chat renders.
PROMPT_VERSION = "cp-v2"
PROMPT_VERSIONS: dict[str, str] = {}


def prompt_version_for(kind: str) -> str:
    return PROMPT_VERSIONS.get(kind, PROMPT_VERSION)

#: Text kinds by scope. The pipeline generates them; the coach serves them.
COMPONENT_TEXT_KINDS = ("lesson_welcome",)
ITEM_TEXT_KINDS = ("lesson_step_intro", "video_summary")
QUESTION_TEXT_KINDS = ("question_intro", "hint_l1", "explanation")

#: Per-kind length caps (chars), enforced at generation AND at load.
TEXT_LENGTH_CAPS = {
    "lesson_welcome": 350,
    "lesson_step_intro": 200,
    "video_summary": 300,
    "question_intro": 200,
    "hint_l1": 200,
    "explanation": 400,
}

#: Keys that must never appear anywhere in a committed shard, at any depth.
FORBIDDEN_KEYS = frozenset({"correctAnswers", "correct_answers", "correct"})

#: Version of the browser-capture format inside ``enrichment``. Bump when the
#: extractor's capture changes shape (e.g. anchors added): carry-over then
#: drops the old capture and the component re-queues for browsing, because a
#: slide whose CONTENT is unchanged would otherwise never gain the new fields.
#: v3: decorative-image area floor + the `diagram` region (applets/canvas/svg).
#: v4: per-element anchor `parts`, scroll dims in capture_viewport, and vision
#: descriptions on graphic media (the bytes themselves are stripped pre-write).
#: v5: `anchor_breakpoints` — document-PIXEL geometry measured at several
#: viewport widths (the CET player transform-scales and centers, so one
#: width's fractions land wrong at any other), content extent measured from
#: painted rects (transforms/inner scrollers never grow scrollHeight), the
#: `input` region, and CET's CSS-modules selector grammar.
#: v6: the grid gains a HEIGHT axis (each breakpoint carries `h`) — methodica
#: FITS the viewport (scale = min(width-fit, height-fit)), so a 700px-tall
#: lesson box renders smaller geometry than any fixed-height capture; the
#: runtime bilinear-interpolates. Height-independent players (CET) yield
#: identical rows per height, making the height axis a natural no-op.
#: v7: `vendor_page_id` — the player's own id for the page, read off its
#: xAPI narration during the walk (CET pages announce `initialized` with an
#: opaque id that exists NOWHERE in the DOM or catalog). Maps live
#: navigation/resume events to catalog items, so the position pointer moves
#: when the learner pages, not only when they answer.
CAPTURE_VERSION = 7

#: Capture formats the runtime still trusts. Serving is compatible one
#: version back so a format bump does not blind every screen while the
#: nightly walk backfills the new fields (v6 geometry is valid v7 geometry;
#: v6 merely lacks vendor_page_id).
CAPTURE_COMPAT = frozenset({6, CAPTURE_VERSION})

#: The pointing vocabulary — static on purpose: the coach tool's enum bakes at
#: import time, and geometry resolution happens server-side per slide. Rects
#: only, never element text (FORBIDDEN_KEYS/PII safe by construction).
ANCHOR_REGIONS = frozenset(
    {"question", "options", "input", "image", "video", "diagram", "table",
     "instruction"})

#: Caps applied to enrichment on the way OUT (lookup time), not in the file —
#: the file keeps the full capture so caps can be tuned without a re-browse.
ENRICHMENT_VISIBLE_TEXT_CAP = 700
ENRICHMENT_MEDIA_MAX = 6
ENRICHMENT_MEDIA_LABEL_CAP = 220  # room for the vision description

_REPO_ROOT = Path(__file__).resolve().parents[3]
DEFAULT_CONFIG_DIR = _REPO_ROOT / "content" / "context"

EXTRACTION_VERDICTS = (
    "extracted", "partial", "launch_404", "frame_blocked",
    "driver_error", "timeout", "not_attempted",
)


# ── keys ─────────────────────────────────────────────────────────────────────

def record_key(component_id: str, item_id: str = "", question_id: str = "") -> str:
    """``component|item|question`` — the codebase's canonical content key
    (tutor_decision.support_question_key), with empty trailing segments for
    item- and component-scoped records."""
    return f"{component_id}|{item_id}|{question_id}"


# ── fingerprints (the ONLY implementations — pipeline and runtime share) ────

def _digest(parts: list[Any]) -> str:
    blob = json.dumps(parts, ensure_ascii=False)
    return hashlib.sha1(blob.encode("utf-8")).hexdigest()[:16]


def compute_fingerprint_question(
    question_text: str,
    screen_title: str,
    sibling_texts: Iterable[str],
    information_to_bot: str,
) -> str:
    """What a question's pre-generated texts react to: its authored content.
    Answers are deliberately not in the blob (see module docstring)."""
    return _digest([
        str(question_text or ""),
        str(screen_title or ""),
        sorted(str(t or "") for t in sibling_texts),
        str(information_to_bot or ""),
    ])


def compute_fingerprint_item(
    title: str,
    content_type: str,
    media_format: str,
    information_to_bot: str,
    question_texts: Iterable[str],
) -> str:
    return _digest([
        str(title or ""),
        str(content_type or ""),
        str(media_format or ""),
        str(information_to_bot or ""),
        sorted(str(t or "") for t in question_texts),
    ])


def compute_fingerprint_component(
    objective_title_he: str,
    component_title: str,
    ordered_item_fingerprints: Iterable[str],
) -> str:
    return _digest([
        str(objective_title_he or ""),
        str(component_title or ""),
        list(ordered_item_fingerprints),
    ])


# ── the correct-answers ban ──────────────────────────────────────────────────

def find_forbidden_key(value: Any, path: str = "$") -> Optional[str]:
    """Path of the first forbidden key anywhere in ``value``, else None."""
    if isinstance(value, dict):
        for key, child in value.items():
            if key in FORBIDDEN_KEYS:
                return f"{path}.{key}"
            found = find_forbidden_key(child, f"{path}.{key}")
            if found:
                return found
    elif isinstance(value, list):
        for index, child in enumerate(value):
            found = find_forbidden_key(child, f"{path}[{index}]")
            if found:
                return found
    return None


def assert_no_correct_answers(shard: dict[str, Any]) -> None:
    found = find_forbidden_key(shard)
    if found:
        raise ValueError(f"correct answers must never enter the config: {found}")


# ── shard validation / IO ────────────────────────────────────────────────────

def _valid_generation_block(block: Any) -> bool:
    return (
        isinstance(block, dict)
        and isinstance(block.get("he"), str) and block["he"].strip()
        and isinstance(block.get("prompt_version"), str)
        and isinstance(block.get("source_fingerprint"), str)
    )


def validate_shard(shard: Any) -> list[str]:
    """Structural problems with one shard document; [] when acceptable."""
    problems: list[str] = []
    if not isinstance(shard, dict):
        return ["shard is not an object"]
    if shard.get("schema_version") != SCHEMA_VERSION:
        problems.append(f"schema_version is {shard.get('schema_version')!r}, "
                        f"expected {SCHEMA_VERSION}")
    if not isinstance(shard.get("lomdot"), list):
        problems.append("lomdot missing or not a list")
        return problems
    for lomda in shard["lomdot"]:
        if not isinstance(lomda, dict) or not lomda.get("component_id"):
            problems.append("lomda without component_id")
            continue
        cid = lomda["component_id"]
        if not isinstance(lomda.get("component_fingerprint"), str):
            problems.append(f"{cid}: missing component_fingerprint")
        for kind, block in (lomda.get("texts") or {}).items():
            if kind not in COMPONENT_TEXT_KINDS or not _valid_generation_block(block):
                problems.append(f"{cid}: bad component text {kind!r}")
        for slide in lomda.get("slides") or []:
            if not isinstance(slide, dict) or not slide.get("item_id"):
                problems.append(f"{cid}: slide without item_id")
                continue
            iid = slide["item_id"]
            if not isinstance(slide.get("fingerprint"), str):
                problems.append(f"{cid}/{iid}: missing fingerprint")
            for kind, block in (slide.get("texts") or {}).items():
                if kind not in ITEM_TEXT_KINDS or not _valid_generation_block(block):
                    problems.append(f"{cid}/{iid}: bad slide text {kind!r}")
            for question in slide.get("questions") or []:
                if not isinstance(question, dict) or not question.get("question_id"):
                    problems.append(f"{cid}/{iid}: question without question_id")
                    continue
                qid = question["question_id"]
                if not isinstance(question.get("fingerprint"), str):
                    problems.append(f"{cid}/{iid}/{qid}: missing fingerprint")
                for kind, block in (question.get("texts") or {}).items():
                    if kind not in QUESTION_TEXT_KINDS or not _valid_generation_block(block):
                        problems.append(f"{cid}/{iid}/{qid}: bad question text {kind!r}")
    return problems


def dump_shard(shard: dict[str, Any]) -> str:
    """The one serializer: deterministic bytes so a no-change pipeline run is a
    no-change commit, guarded against correct answers on the way out."""
    assert_no_correct_answers(shard)
    ordered = dict(shard)
    if isinstance(ordered.get("lomdot"), list):
        ordered["lomdot"] = sorted(
            ordered["lomdot"], key=lambda l: str(l.get("component_id") or ""))
    return json.dumps(ordered, ensure_ascii=False, indent=2, sort_keys=False) + "\n"


def shard_paths(config_dir: Path) -> list[Path]:
    if not config_dir.is_dir():
        return []
    return sorted(p for p in config_dir.rglob("*.json") if p.name != "index.json")


# ── diff (pipeline-side, pure) ───────────────────────────────────────────────

def diff_components(
    catalog: dict[str, str], config: dict[str, str],
) -> dict[str, list[str]]:
    """component_id → fingerprint on both sides → what the nightly run must do."""
    return {
        "new": sorted(cid for cid in catalog if cid not in config),
        "changed": sorted(cid for cid in catalog
                          if cid in config and config[cid] != catalog[cid]),
        "removed": sorted(cid for cid in config if cid not in catalog),
    }


# ── runtime: load once, look up per message ──────────────────────────────────

_STATE: dict[str, Any] = {"loaded": False, "records": {}, "meta": {}}


def enabled() -> bool:
    """Kill switch only — the fingerprint gate is the real safety mechanism."""
    return (os.getenv("CONTENT_INTEL_ENABLED") or "1").strip().lower() not in {
        "0", "false", "no", "off",
    }


def _config_dir() -> Path:
    override = (os.getenv("CONTENT_INTEL_CONFIG_PATH") or "").strip()
    return Path(override) if override else DEFAULT_CONFIG_DIR


def _index_shard(shard: dict[str, Any], records: dict[str, dict[str, Any]]) -> None:
    for lomda in shard.get("lomdot") or []:
        cid = str(lomda.get("component_id") or "")
        if not cid:
            continue
        records[record_key(cid)] = {
            "scope": "component",
            "fingerprint": lomda.get("component_fingerprint"),
            "texts": lomda.get("texts") or {},
        }
        for slide in lomda.get("slides") or []:
            iid = str(slide.get("item_id") or "")
            if not iid:
                continue
            records[record_key(cid, iid)] = {
                "scope": "item",
                "component_id": cid,
                "item_id": iid,
                "fingerprint": slide.get("fingerprint"),
                "texts": slide.get("texts") or {},
                "enrichment": slide.get("enrichment"),
                "question_ids": [
                    str(q.get("question_id"))
                    for q in slide.get("questions") or [] if q.get("question_id")
                ],
                # Ordered question texts — what makes two slides the SAME
                # learner-visible exercise (kata_catalog._variant_signature's
                # notion); the vendor-page-id ambiguity guard compares these.
                "question_texts": tuple(
                    " ".join(str((q or {}).get("question_text") or "").split())
                    for q in slide.get("questions") or []
                ),
            }
            for question in slide.get("questions") or []:
                qid = str(question.get("question_id") or "")
                if not qid:
                    continue
                records[record_key(cid, iid, qid)] = {
                    "scope": "question",
                    "component_id": cid,
                    "item_id": iid,
                    "question_id": qid,
                    "fingerprint": question.get("fingerprint"),
                    "texts": question.get("texts") or {},
                }


def _ensure_loaded() -> None:
    if _STATE["loaded"]:
        return
    _STATE["loaded"] = True  # one attempt per process; failures stay empty
    records: dict[str, dict[str, Any]] = {}
    directory = _config_dir()
    for path in shard_paths(directory):
        try:
            shard = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            print(f"⚠️ content-intel shard unreadable, skipping {path.name}: {exc}")
            continue
        smuggled = find_forbidden_key(shard)
        if smuggled:
            # A poisoned file must not half-work — drop the whole thing.
            print(f"⚠️ content-intel shard {path.name} contains {smuggled}; discarded")
            continue
        problems = validate_shard(shard)
        if problems:
            print(f"⚠️ content-intel shard {path.name} invalid ({problems[0]}); discarded")
            continue
        _index_shard(shard, records)
    _STATE["records"] = records
    # Player page id → catalog item, per component (v7 `vendor_page_id`).
    # An id equality is content-neutral, so no freshness gate: a stale id
    # simply never matches again, while a matching one names the same page.
    # An id claimed by slides that are NOT variants of one another names at
    # most one of them (measured 2026-09-01: a walk stuck on a drag-gated
    # page stamped its id on four different slides) — such claims are dropped
    # entirely; moving a live learner's pointer to the wrong item is worse
    # than not moving it. Variant siblings genuinely share their physical
    # page: the first claims it, the variants hedge covers the ambiguity.
    claims: dict[tuple[str, str], list[dict[str, Any]]] = {}
    for key, record in records.items():
        enrichment_blob = record.get("enrichment")
        vendor_id = (enrichment_blob or {}).get("vendor_page_id") \
            if isinstance(enrichment_blob, dict) else ""
        if vendor_id:
            component_key, item_key = key.split("|")[0:2]
            if item_key:
                claims.setdefault((component_key, str(vendor_id)), []).append(
                    {"item": item_key, "record": record})
    vendor_screens: dict[tuple[str, str], str] = {}
    for claim_key, claimants in claims.items():
        signatures = {
            tuple(c["record"].get("question_texts") or ()) for c in claimants}
        if len(claimants) > 1 and (len(signatures) != 1
                                   or not any(any(s) for s in signatures)):
            continue
        vendor_screens[claim_key] = claimants[0]["item"]
    _STATE["vendor_screens"] = vendor_screens
    index_path = directory / "index.json"
    if index_path.exists():
        try:
            _STATE["meta"] = json.loads(index_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            _STATE["meta"] = {}
    if records:
        print(f"🧠 content-intel: {len(records)} records loaded from {directory}")


def _live_fingerprint(record: dict[str, Any]) -> Optional[str]:
    """Recompute the record's fingerprint from the live catalog snapshot.

    Uses the RAW snapshot values (never the bundle's safe_text-truncated
    copies, which would break hash equality). Callers on the coach path have
    already awaited ``kata_catalog.ensure_loaded()`` — ``build_coach_bundle``
    does — so these reads are sync dictionary lookups. A cold snapshot returns
    None → treated as not-fresh → live generation.
    """
    from app.services import kata_catalog

    scope = record.get("scope")
    cid = record.get("component_id") or record.get("key", "").split("|")[0]
    try:
        if scope == "question":
            iid, qid = record["item_id"], record["question_id"]
            questions = kata_catalog.questions_for_item(cid, iid)
            if not questions:
                return None
            texts = [str(q.get("questionText") or "").strip() for q in questions]
            mine = next((i for i, q in enumerate(questions)
                         if q.get("questionId") == qid), None)
            if mine is None:
                return None
            profile = kata_catalog.item_profile(cid, iid)
            return compute_fingerprint_question(
                texts[mine],
                str(profile.get("title") or ""),
                [t for i, t in enumerate(texts) if i != mine and t],
                kata_catalog.information_for_item(cid, iid) or "",
            )
        if scope == "item":
            iid = record["item_id"]
            profile = kata_catalog.item_profile(cid, iid)
            if not profile.get("id"):
                return None
            questions = kata_catalog.questions_for_item(cid, iid)
            return compute_fingerprint_item(
                str(profile.get("title") or ""),
                str(profile.get("content_type") or ""),
                str(profile.get("media_format") or ""),
                kata_catalog.information_for_item(cid, iid) or "",
                [str(q.get("questionText") or "").strip() for q in questions],
            )
        # component scope
        component = kata_catalog.get_component(cid)
        if not component:
            return None
        item_prints = []
        for profile in kata_catalog.item_profiles(cid):
            iid = profile.get("id")
            questions = kata_catalog.questions_for_item(cid, iid)
            item_prints.append(compute_fingerprint_item(
                str(profile.get("title") or ""),
                str(profile.get("content_type") or ""),
                str(profile.get("media_format") or ""),
                kata_catalog.information_for_item(cid, iid) or "",
                [str(q.get("questionText") or "").strip() for q in questions],
            ))
        return compute_fingerprint_component(
            kata_catalog.localized_objective_title(
                str(component.get("objective_id") or ""), "he"),
            str(component.get("title") or ""),
            item_prints,
        )
    except Exception:  # pragma: no cover - freshness must never raise
        return None


def is_fresh(key: str, record: dict[str, Any]) -> bool:
    record = dict(record, key=key)
    live = _live_fingerprint(record)
    return live is not None and live == record.get("fingerprint")


def pregen_text(
    kind: str,
    component_id: str,
    item_id: str = "",
    question_id: str = "",
) -> Optional[dict[str, Any]]:
    """A servable pre-generated Hebrew text, or None → generate live.

    None covers every miss: flag off, no config, unknown key, kind absent,
    prompt-version drift, and content drift (fingerprint mismatch against the
    live catalog). The caller never needs to know which.
    """
    if not enabled():
        return None
    _ensure_loaded()
    key = record_key(component_id, item_id, question_id)
    record = _STATE["records"].get(key)
    if not record:
        return None
    block = (record.get("texts") or {}).get(kind)
    if not _valid_generation_block(block):
        return None
    if block.get("prompt_version") != prompt_version_for(kind):
        return None
    if block.get("source_fingerprint") != record.get("fingerprint"):
        return None  # the file itself is internally inconsistent
    if not is_fresh(key, record):
        return None
    text = block["he"].strip()
    cap = TEXT_LENGTH_CAPS.get(kind)
    if cap and len(text) > cap:
        return None
    return {"text": text, "fingerprint": record["fingerprint"], "kind": kind}


def vendor_screen_item(component_id: str, vendor_tail: str) -> Optional[str]:
    """Map a player's page id (the tail of its xAPI object) to the catalog
    item whose slide announced that id during the nightly walk, or None.

    CET narrates navigation with opaque per-page ids that exist nowhere else
    — not in the DOM, not in the catalog. The walk overhears them on the
    wire; this lookup is what lets a live learner's page change (or resume)
    move ``current_state`` instead of leaving the coach a screen behind.
    """
    if not enabled() or not component_id or not vendor_tail:
        return None
    _ensure_loaded()
    return (_STATE.get("vendor_screens") or {}).get(
        (str(component_id), str(vendor_tail)))


def single_question_id(component_id: str, item_id: str) -> Optional[str]:
    """The slide's only question id, or None when it has zero or several."""
    if not enabled():
        return None
    _ensure_loaded()
    record = _STATE["records"].get(record_key(component_id, item_id))
    ids = (record or {}).get("question_ids") or []
    return str(ids[0]) if len(ids) == 1 else None


def arrival_question_id(
    component_id: str, item_id: str, pointed_question_id: str = ""
) -> Optional[str]:
    """The question an ARRIVING learner faces on this slide, or None.

    The screen_change push is ``component|item``, so on arrival the brain's
    question pointer is empty or still names the PREVIOUS screen — and a slide
    that holds several questions (סעיף א/ב) used to defeat the pregen intro
    entirely. But arrival has a known position: the learner lands at the TOP,
    which is the slide's first question in catalog order — the same grounding
    the live path chooses when it cannot locate them.

    When the pointer names a question that IS on this slide, the learner is
    mid-screen, not arriving — return None and let the pointed question's own
    text (or its live fallback) speak; guessing "part 1" at someone on part 3
    would re-open the whole screen on them.
    """
    if not enabled():
        return None
    _ensure_loaded()
    record = _STATE["records"].get(record_key(component_id, item_id))
    ids = [str(q) for q in (record or {}).get("question_ids") or []]
    if not ids:
        return None
    if pointed_question_id and pointed_question_id in ids:
        return None
    return ids[0]


def enrichment(component_id: str, item_id: str) -> Optional[dict[str, Any]]:
    """Browser-extracted slide context for the live model, bounded, or None."""
    if not enabled():
        return None
    _ensure_loaded()
    key = record_key(component_id, item_id)
    record = _STATE["records"].get(key)
    if not record:
        return None
    raw = record.get("enrichment")
    if not isinstance(raw, dict):
        return None
    if not is_fresh(key, record):
        return None  # stale enrichment is worse misgrounding than none
    visible = str(raw.get("visible_text") or "").strip()
    media: list[str] = []
    for entry in (raw.get("media") or [])[:ENRICHMENT_MEDIA_MAX]:
        if not isinstance(entry, dict):
            continue
        kind = str(entry.get("kind") or "media")
        label = str(entry.get("title") or entry.get("alt") or "").strip()
        # The vision description — what the picture/diagram actually shows —
        # is the difference between "image:" and an answerable "מה רואים פה?".
        description = str(entry.get("description") or "").strip()
        if description:
            label = f"{label} — {description}" if label else description
        duration = entry.get("duration_seconds")
        suffix = f" ({int(duration)}s)" if isinstance(duration, (int, float)) else ""
        media.append(f"{kind}: {label}"[:ENRICHMENT_MEDIA_LABEL_CAP] + suffix)
    if not visible and not media:
        return None
    return {
        "visible_text": visible[:ENRICHMENT_VISIBLE_TEXT_CAP],
        "media": media,
    }


#: Sanity ceiling for capture pixel values — a coordinate beyond this is a
#: corrupt capture, not a big screen.
_ANCHOR_PIXEL_MAX = 8000


def screen_anchors(component_id: str, item_id: str) -> Optional[dict[str, Any]]:
    """The slide's pointing geometry, or None → whole-frame degradation.

    Serves only what the overlay can trust: a fresh capture (same fingerprint
    gate as ``enrichment``) in the CURRENT capture format, every value a sane
    document PIXEL, every region from ``ANCHOR_REGIONS``. Geometry comes per
    capture WIDTH (the extractor measures the same screen at several viewport
    sizes); the runtime bilinear-interpolates its live box between the
    surrounding samples. The returned shape is what the coach route puts on
    the wire::

        {"regions": {region: [{"w", "h", "content_w", "content_h",
                               "rect": {x,y,w,h}, "parts"?: [rect, …]}, …]}}
    """
    if not enabled():
        return None
    _ensure_loaded()
    key = record_key(component_id, item_id)
    record = _STATE["records"].get(key)
    if not record:
        return None
    raw = record.get("enrichment")
    if not isinstance(raw, dict) or raw.get("capture_version") not in CAPTURE_COMPAT:
        return None
    if not is_fresh(key, record):
        return None  # stale geometry points at the wrong thing — worse than none

    def _pixel_rect(rect: Any) -> Optional[dict[str, float]]:
        if not isinstance(rect, dict):
            return None
        try:
            out = {axis: min(float(_ANCHOR_PIXEL_MAX),
                             max(0.0, float(rect[axis])))
                   for axis in ("x", "y", "w", "h")}
        except (KeyError, TypeError, ValueError):
            return None
        return out if out["w"] > 0 and out["h"] > 0 else None

    regions: dict[str, list[dict[str, Any]]] = {}
    for bp in raw.get("anchor_breakpoints") or []:
        if not isinstance(bp, dict):
            continue
        try:
            width = int(bp.get("w") or 0)
            height = int(bp.get("h") or 0)
            content_w = int(bp.get("content_w") or 0)
            content_h = int(bp.get("content_h") or 0)
        except (TypeError, ValueError):
            continue
        if not (0 < width <= _ANCHOR_PIXEL_MAX
                and 0 < height <= _ANCHOR_PIXEL_MAX
                and content_w > 0 and content_h > 0):
            continue
        for anchor in bp.get("anchors") or []:
            if not isinstance(anchor, dict):
                continue
            region = str(anchor.get("region") or "")
            rect = _pixel_rect(anchor.get("rect"))
            if region not in ANCHOR_REGIONS or rect is None:
                continue
            entry: dict[str, Any] = {
                "w": width, "h": height,
                "content_w": content_w, "content_h": content_h,
                "rect": rect,
            }
            parts = [p for p in (_pixel_rect(part)
                                 for part in anchor.get("parts") or [])
                     if p is not None][:8]
            if parts:
                entry["parts"] = parts
            regions.setdefault(region, []).append(entry)
    # One entry per grid point per region, sorted — interpolation needs order.
    for region, entries in regions.items():
        seen: dict[tuple[int, int], dict[str, Any]] = {}
        for entry in entries:
            seen.setdefault((entry["w"], entry["h"]), entry)
        regions[region] = sorted(seen.values(),
                                 key=lambda e: (e["w"], e["h"]))
    regions = {region: entries for region, entries in regions.items() if entries}
    if not regions:
        return None
    return {"regions": regions}


async def record_pregen_hit(usage_context: Any, kind: str, text: str) -> None:
    """One measurable event per served pregen text — the optimization's meter.

    Recorded through ai_usage (provider ``pregen_cache``) so the admin usage
    dashboards can chart hits next to ``coach.proactive``'s live calls.
    Fire-and-forget semantics; never raises into the serving path.
    """
    try:
        from app.services import ai_usage

        await ai_usage.record_usage(
            context=usage_context.for_operation("coach.pregen_hit"),
            timer=ai_usage.UsageTimer.start(),
            provider="pregen_cache",
            gateway="local",
            deployment=kind,
            api_version=None,
            streaming=False,
            meter="characters",
            status="completed",
            usage_status="not_applicable",
            quantity=len(text),
            quantity_unit="characters",
        )
    except Exception:  # pragma: no cover - metering must never break serving
        pass


def reset_for_tests() -> None:
    _STATE["loaded"] = False
    _STATE["records"] = {}
    _STATE["meta"] = {}
    _STATE["vendor_screens"] = {}
