import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import test from 'node:test'
import { fileURLToPath } from 'node:url'
import { TravelStateMachine } from '../src/features/Yuvi-studio/travel/TravelStateMachine.ts'

const SRC = fileURLToPath(new URL('../src/', import.meta.url))
const machine = readFileSync(join(SRC, 'features/Yuvi-studio/travel/TravelStateMachine.ts'), 'utf8')
const controller = readFileSync(join(SRC, 'features/Yuvi-studio/travel/FriendTravelController.ts'), 'utf8')
const visuals = readFileSync(join(SRC, 'features/Yuvi-studio/travel/TravelVisualFX.ts'), 'utf8')
const portal = readFileSync(join(SRC, 'features/Yuvi-studio/travel/PortalEffect.ts'), 'utf8')
const labRoom = readFileSync(join(SRC, 'features/Yuvi-studio/YuviLabRoom.ts'), 'utf8')

test('travel lifecycle is deterministic and interruptible', () => {
  assert.match(machine, /idle: \['portalOpening'\]/)
  assert.match(machine, /portalOpening: \['yobiEntering', 'portalCooldown', 'idle'\]/)
  assert.match(machine, /yobiEntering: \['worldSwap', 'idle'\]/)
  assert.match(machine, /worldSwap: \['yobiExiting', 'idle'\]/)
  assert.match(machine, /landing: \['portalClosing', 'idle'\]/)
  assert.match(machine, /portalCooldown: \['idle'\]/)
  assert.match(machine, /portalClosing: \['idle'\]/)
  assert.match(controller, /if \(this\.busy\) return false/)
  assert.match(controller, /let destinationLoaded = !destinationReady/)
  assert.match(controller, /if \(!destinationLoaded\(\)\) this\.timeline\?\.pause\(\)/)
  assert.match(controller, /if \(this\.timeline\?\.paused\(\)\) this\.timeline\.play\(\)/)
  assert.match(controller, /\}, \(\) => this\.cooldown\(handlers\)\)/)
  assert.match(controller, /handlers\.onFailure\?\.\(\)/)
  assert.match(controller, /\.call\(handlers\.onWorldSwap\)/)
  assert.match(controller, /startTeleport\(handlers/)
  assert.match(controller, /playPhaseShift\(move, clock\)/)
  assert.match(controller, /shrinkIntoPortal\(move, handlers/)
  assert.match(controller, /materializeFromPortal\(move, clock\)/)
  assert.match(controller, /finishTeleport\(move, clock\)/)
  assert.match(controller, /cancel\(handlers\?/)
  assert.match(controller, /this\.timeline\?\.kill\(\)/)
})

test('state machine rejects repeated travel and recovers after cancellation', () => {
  const travel = new TravelStateMachine()
  assert.equal(travel.move('portalOpening'), true)
  assert.equal(travel.move('portalOpening'), false)
  assert.equal(travel.move('portalCooldown'), true)
  travel.reset()
  assert.equal(travel.phase, 'idle')
  assert.equal(travel.move('portalOpening'), true)
})

test('travel effects use the existing renderer without tinting the room', () => {
  assert.match(visuals, /new PortalEffect\(reducedMotion\)/)
  assert.match(visuals, /sourcePortalPosition/)
  assert.match(visuals, /destinationPortalPosition/)
  assert.match(visuals, /captureAvatarParticles\(\)/)
  assert.match(visuals, /this\.robot\.scale\.copy\(this\.originalScale\)\.multiplyScalar\(Math\.max\(0, 1 - progress\)\)/)
  assert.match(visuals, /Math\.sin\(progress \* Math\.PI\) \* 0\.45/)
  assert.match(visuals, /this\.captureArrivalTransform\(\)/)
  assert.doesNotMatch(visuals, /private captureArrivalTransform\(\) \{[\s\S]{0,160}this\.originalScale\.copy\(this\.robot\.scale\)/)
  assert.match(visuals, /private readonly capsuleAnchor/)
  assert.match(visuals, /this\.sourcePortalPosition\.copy\(this\.capsuleAnchor\(\)/)
  assert.match(visuals, /this\.destinationPortalPosition\.copy\(this\.capsuleAnchor\(\)/)
  assert.match(visuals, /this\.sourcePortal\.close\(1\)/)
  assert.match(visuals, /this\.destinationPortal\.close\(1\)/)
  assert.match(visuals, /if \(phase === 'worldSwap'\) \{[\s\S]{0,120}this\.sourcePortal\.close\(1\)[\s\S]{0,120}this\.destinationPortal\.close\(1\)/)
  assert.match(visuals, /if \(phase === 'yobiExiting'\) \{[\s\S]{0,120}this\.sourcePortal\.close\(1\)/)
  assert.doesNotMatch(visuals, /private portalBesideYobi/)
  assert.match(visuals, /this\.destinationPortal\.close\(progress\)/)
  assert.match(portal, /new THREE\.CircleGeometry/)
  assert.doesNotMatch(portal, /this\.center\.rotation\.x/)
  assert.doesNotMatch(portal, /ring\.rotation\.x = Math\.PI \/ 2/)
  assert.match(portal, /color: 0x000000/)
  assert.match(portal, /side: THREE\.DoubleSide/)
  assert.match(portal, /this\.group\.quaternion\.copy\(camera\.quaternion\)/)
  assert.match(portal, /new THREE\.TorusGeometry/)
  assert.match(portal, /new THREE\.Points/)
  assert.match(portal, /dispose\(\)/)
  assert.match(visuals, /renderer\.render\(this\.scene, this\.camera\)/)
  assert.doesNotMatch(visuals, /EffectComposer|UnrealBloomPass|AfterimagePass/)
  assert.doesNotMatch(visuals, /new THREE\.WebGLRenderer/)
})

test('the World Capsule Gate owns the physical portal machine', () => {
  assert.match(labRoom, /setMissionTravel/)
  assert.match(labRoom, /missionPortalAnchor/)
  assert.match(labRoom, /missionPortal\.position\.set/)
  assert.match(labRoom, /roomItemSpec\('worldCapsuleGate'\)/)
  assert.match(labRoom, /mission\.scale\.setScalar\(PROP_SCALE\)/)
  assert.match(labRoom, /mission\?\.position\.set\(stations\.mission\.x/)
})