import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import test from 'node:test'
import { fileURLToPath } from 'node:url'
import { TravelStateMachine } from '../src/features/Yuvi-studio/travel/TravelStateMachine.ts'

const SRC = fileURLToPath(new URL('../src/', import.meta.url))
const machine = readFileSync(join(SRC, 'features/Yuvi-studio/travel/TravelStateMachine.ts'), 'utf8')
const controller = readFileSync(join(SRC, 'features/Yuvi-studio/travel/FriendTravelController.ts'), 'utf8')
const visuals = readFileSync(join(SRC, 'features/Yuvi-studio/travel/TravelVisualFX.ts'), 'utf8')
const portal = readFileSync(join(SRC, 'features/Yuvi-studio/travel/PortalEffect.ts'), 'utf8')
const labRoom = readFileSync(join(SRC, 'features/Yuvi-studio/YuviLabRoom.ts'), 'utf8')
const planetarium = readFileSync(join(SRC, 'features/Yuvi-studio/DomePlanetarium.ts'), 'utf8')
const studio = readFileSync(join(SRC, 'features/Yuvi-studio/StudioContent.tsx'), 'utf8')
const avatar = readFileSync(join(SRC, 'features/Yuvi-studio/YuviAvatar3D.tsx'), 'utf8')
const studioCss = readFileSync(join(SRC, 'styles/Yuvi-studio.css'), 'utf8')

test('travel lifecycle is deterministic and interruptible', () => {
  assert.match(machine, /idle: \['portalOpening'\]/)
  assert.match(machine, /portalOpening: \['yobiEntering', 'portalCooldown', 'idle'\]/)
  assert.match(machine, /yobiEntering: \['worldSwap', 'idle'\]/)
  assert.match(machine, /worldSwap: \['yobiExiting', 'idle'\]/)
  assert.match(machine, /landing: \['portalClosing', 'idle'\]/)
  assert.match(machine, /portalCooldown: \['idle'\]/)
  assert.match(machine, /portalClosing: \['idle'\]/)
  assert.match(controller, /if \(this\.busy\) return false/)
  assert.match(controller, /let destinationLoaded = !destinationReady/)
  assert.match(controller, /if \(!destinationLoaded\(\)\) this\.timeline\?\.pause\(\)/)
  assert.match(controller, /if \(this\.timeline\?\.paused\(\)\) this\.timeline\.play\(\)/)
  assert.match(controller, /\}, \(\) => this\.cooldown\(handlers\)\)/)
  assert.match(controller, /handlers\.onFailure\?\.\(\)/)
  assert.match(controller, /\.call\(handlers\.onWorldSwap\)/)
  assert.match(controller, /startTeleport\(handlers/)
  assert.match(controller, /playPhaseShift\(move, clock\)/)
  assert.match(controller, /shrinkIntoPortal\(move, handlers/)
  assert.match(controller, /materializeFromPortal\(move, clock\)/)
  assert.match(controller, /finishTeleport\(move, clock\)/)
  assert.match(controller, /cancel\(handlers\?/)
  assert.match(controller, /this\.timeline\?\.kill\(\)/)
})

test('state machine rejects repeated travel and recovers after cancellation', () => {
  const travel = new TravelStateMachine()
  assert.equal(travel.move('portalOpening'), true)
  assert.equal(travel.move('portalOpening'), false)
  assert.equal(travel.move('portalCooldown'), true)
  travel.reset()
  assert.equal(travel.phase, 'idle')
  assert.equal(travel.move('portalOpening'), true)
})

test('travel effects use the existing renderer without tinting the room', () => {
  assert.match(visuals, /new PortalEffect\(reducedMotion\)/)
  assert.match(visuals, /sourcePortalPosition/)
  assert.match(visuals, /destinationPortalPosition/)
  assert.match(visuals, /captureAvatarParticles\(\)/)
  assert.match(visuals, /this\.robot\.scale\.copy\(this\.originalScale\)\.multiplyScalar\(Math\.max\(0, 1 - progress\)\)/)
  assert.match(visuals, /Math\.sin\(progress \* Math\.PI\) \* 0\.45/)
  assert.match(visuals, /this\.captureArrivalTransform\(\)/)
  assert.match(visuals, /this\.originalPosition\.copy\(this\.destinationPortalPosition\)/)
  assert.match(visuals, /this\.arrivalFloorPosition\.copy\(this\.capsuleApproach\(\) \?\? this\.originalPosition\)/)
  assert.match(visuals, /const descent = Math\.min\(elapsed \/ 0\.38, 1\)/)
  assert.match(controller, /duration: 0\.38, ease: 'power2\.in'/)
  assert.doesNotMatch(visuals, /private captureArrivalTransform\(\) \{[\s\S]{0,160}this\.originalScale\.copy\(this\.robot\.scale\)/)
  assert.match(visuals, /private readonly capsuleAnchor/)
  assert.match(visuals, /this\.sourcePortalPosition\.copy\(this\.capsuleAnchor\(\)/)
  assert.match(visuals, /this\.sourceRobotTarget\.copy\(this\.sourcePortalPosition\)/)
  assert.match(visuals, /this\.robot\.position\.lerpVectors\(this\.originalPosition, this\.sourceRobotTarget, progress\)/)
  assert.match(visuals, /this\.destinationPortalPosition\.copy\(this\.capsuleAnchor\(\)/)
  assert.match(visuals, /private readonly isArrivalAnchorReady: \(\) => boolean/)
  assert.match(visuals, /if \(this\.arrivalPending && this\.isArrivalAnchorReady\(\)\)/)
  assert.match(visuals, /this\.sourcePortal\.close\(1\)/)
  assert.match(visuals, /this\.destinationPortal\.close\(1\)/)
  assert.match(visuals, /if \(phase === 'worldSwap'\) \{[\s\S]{0,120}this\.sourcePortal\.close\(1\)[\s\S]{0,120}this\.destinationPortal\.close\(1\)/)
  assert.match(visuals, /if \(phase === 'yobiExiting'\) \{[\s\S]{0,120}this\.sourcePortal\.close\(1\)/)
  assert.doesNotMatch(visuals, /private portalBesideYobi/)
  assert.match(visuals, /this\.destinationPortal\.close\(progress\)/)
  assert.match(portal, /new THREE\.CircleGeometry/)
  assert.doesNotMatch(portal, /this\.center\.rotation\.x/)
  assert.doesNotMatch(portal, /ring\.rotation\.x = Math\.PI \/ 2/)
  assert.match(portal, /new THREE\.ShaderMaterial/)
  assert.match(portal, /collapse: \{ value: 0 \}/)
  assert.match(portal, /side: THREE\.DoubleSide/)
  assert.match(portal, /this\.group\.quaternion\.copy\(camera\.quaternion\)/)
  assert.match(portal, /new THREE\.TorusGeometry/)
  assert.match(portal, /new THREE\.Points/)
  assert.match(portal, /dispose\(\)/)
  assert.match(visuals, /renderer\.render\(this\.scene, this\.camera\)/)
  assert.doesNotMatch(visuals, /EffectComposer|UnrealBloomPass|AfterimagePass/)
  assert.doesNotMatch(visuals, /new THREE\.WebGLRenderer/)
})

test('the World Capsule Gate owns the physical portal machine', () => {
  assert.match(labRoom, /setMissionTravel/)
  assert.match(labRoom, /missionPortalAnchor/)
  assert.match(labRoom, /const MISSION_APPROACH_RADIUS = 2\.75/)
  assert.match(labRoom, /zone\.radius = zone\.id === 'mission' \? MISSION_APPROACH_RADIUS/)
  assert.match(labRoom, /missionPortal\.position\.set/)
  assert.match(labRoom, /roomItemSpec\('worldCapsuleGate'\)/)
  assert.match(labRoom, /mission\.scale\.setScalar\(PROP_SCALE\)/)
  assert.match(labRoom, /mission\?\.position\.set\(stations\.mission\.x/)
})

test('each room layout paints only its own floor surface', () => {
  assert.match(labRoom, /let floorStyleMaterial: THREE\.MeshBasicMaterial \| THREE\.MeshStandardMaterial = floorMat/)
  assert.match(labRoom, /const shellFloorMaterial = track\(new THREE\.MeshBasicMaterial/)
  assert.match(labRoom, /layoutId === 'dome'\s+\? new THREE\.CircleGeometry\(shellRadius, 64\)\s+: new THREE\.ShapeGeometry\(shape\)/)
  assert.match(labRoom, /const outlinePoints = layoutId === 'dome'/)
  assert.match(labRoom, /floorStyleMaterial = shellFloorMaterial/)
  assert.match(labRoom, /floorStyleMaterial\.map = layoutId === 'triangularObservatory'[\s\S]{0,100}\? null[\s\S]{0,100}: texture \?\? \(layoutId === 'lab' \? floorTexture : null\)/)
  assert.doesNotMatch(labRoom, /floorSkinMat|floorSkin\.visible/)
})

test('floor layers use explicit depth separation to avoid zoomed-out flicker', () => {
  assert.match(labRoom, /grid\.position\.set\(0, FLOOR_Y \+ 0\.032, MID_Z\)/)
  assert.match(labRoom, /pool\.position\.set\(0, FLOOR_Y \+ 0\.024, 0\)/)
  assert.match(labRoom, /grid\.renderOrder = 2/)
  assert.match(labRoom, /shellFloor\.receiveShadow = false/)
  assert.doesNotMatch(labRoom, /new THREE\.ShadowMaterial/)
})

test('the studio camera does not clip the room-scale dome and sky shells', () => {
  assert.match(avatar, /new THREE\.PerspectiveCamera\(30, 1, 0\.1, 220\)/)
  assert.match(avatar, /projectPointIntoLayout\(activeLayout, \{ x: camera\.position\.x, z: camera\.position\.z \}, 0\.8\)/)
  assert.match(labRoom, /horizon\.visible = layoutId === 'lab'/)
  assert.doesNotMatch(labRoom, /opacity: 0\.88/)
})

test('the triangular observatory is a closed technical shell', () => {
  assert.match(labRoom, /const wallTopY = FLOOR_Y \+ 7\.6/)
  assert.match(labRoom, /color: layoutId === 'dome' \? 0x08152a : 0x000000/)
  assert.match(labRoom, /floorStyleMaterial\.map = layoutId === 'triangularObservatory'[\s\S]{0,80}\? null/)
  assert.match(labRoom, /const observatoryPanels = \[0x162b46, 0x10243c, 0x1b3552\]/)
  assert.match(labRoom, /color: 0x7fe4ff/)
  assert.match(labRoom, /color: 0x8ef2b0/)
  assert.match(labRoom, /face\(\[bottomStart, bottomEnd, topEnd, topStart\]/)
  assert.match(labRoom, /face\(\[topStart, topEnd, apex\]/)
})

test('the dome planetarium uses the learner brain without leaking progress into visitor rooms', () => {
  assert.match(studio, /const \{ brain \} = useBrain\(\)/)
  assert.match(studio, /Object\.values\(brain\?\.progress \?\? \{\}\)/)
  assert.match(studio, /planetariumProgress=\{visitorRoom \? null : planetariumProgress\}/)
  assert.match(avatar, /planetariumProgress,\s+accent: initialDesign\.colors\.glow/)
  assert.match(labRoom, /createDomePlanetarium\(\{/)
  assert.match(labRoom, /planetarium\?\.setStations\(stations\)/)
  assert.match(labRoom, /planetarium\?\.setMood\(style\.mood\)/)
  assert.match(labRoom, /planetarium\?\.update\(t\)/)
})

test('the dome planetarium keeps its complete visual and performance contract', () => {
  assert.match(planetarium, /evidence-constellation/)
  assert.match(planetarium, /central-holographic-planet/)
  assert.match(planetarium, /curved-station-paths/)
  assert.match(planetarium, /brass-observatory-ribs/)
  assert.match(planetarium, /restrained-planetarium-horizon/)
  assert.match(planetarium, /const MOODS: Record<MoodId/)
  assert.match(planetarium, /if \(reduceMotion\) return/)
  assert.match(planetarium, /const ambientCount = rich \? 110 : 54/)
  assert.match(planetarium, /if \(!rich\) planet\.scale\.setScalar\(0\.5\)/)
})

test('room travel keeps Yuvi grounded in front of the ring before extraction', () => {
  assert.match(studio, /avatarRef\.current\?\.walkToMissionPortal\(\(\) =>/)
  assert.match(studio, /requestAnimationFrame\(\(\) => avatarRef\.current\?\.teleportToMissionPortal\(destination\.owner_id\)\)/)
  assert.match(avatar, /const approach = room\?\.missionPortalApproach\(\)/)
  assert.match(avatar, /nextZone === 'mission' \? room\?\.missionPortalApproach\(\) : null/)
  assert.match(avatar, /const missionLift = 0/)
})

test('both directions resolve the live World Capsule anchor', () => {
  assert.match(avatar, /walkToMissionPortal: \(onArrival\?: \(\) => void\) => void/)
  assert.match(avatar, /teleportToMissionPortal: \(roomId\?: string\) => void/)
  assert.match(avatar, /const anchor = room\?\.missionPortalAnchor\(\)/)
  assert.match(avatar, /pendingMissionPortalRoomId === roomIdRef\.current && appliedStations === stationsRef\.current/)
  assert.match(studio, /roomId=\{currentRoomId\}/)
  assert.match(studio, /const homeRoomId = user\?\.user_id \?\? 'home'/)
  assert.match(studio, /const currentRoomId = visitorRoom\?\.owner_id \?\? homeRoomId/)
  assert.match(studio, /if \(zone === 'mission' && visitingAnotherRoom && travelPhase === 'idle'\) returnToOwnRoom\(\)/)
  assert.match(studio, /avatarRef\.current\?\.setVisitorHost\(null\)/)
  assert.doesNotMatch(studio, /FRIEND_ROOM_LANDING|FRIENDS_STATION_RETURN/)
})

test('visitor room owner uses visual-only ambient movement through curated room waypoints', () => {
  assert.match(labRoom, /ambientWaypoints: \(\) => Array<\{ x: number; z: number; lookAtX: number; lookAtZ: number \}>/)
  assert.match(labRoom, /const ambientWaypoints = \(\) =>/)
  assert.match(labRoom, /const clear = blockers\(\)\.every/)
  assert.match(avatar, /let visitorAmbient:/)
  assert.match(avatar, /const advanceVisitorAmbient = \(t: number, dt: number\) =>/)
  assert.match(avatar, /const options = \(room\?\.ambientWaypoints\(\) \?\? \[\]\)/)
  assert.match(avatar, /hostPathIsClear\(hostPosition, waypoint\)/)
  assert.match(avatar, /const spawn = \(room\?\.ambientWaypoints\(\) \?\? \[\]\)\.find/)
  assert.match(avatar, /advanceVisitorAmbient\(t, dt\)/)
})

test('My Worlds projects living Three.js destinations instead of opening a modal', () => {
  const hologram = readFileSync(join(SRC, 'features/Yuvi-studio/HolographicWorldSelector.tsx'), 'utf8')
  assert.doesNotMatch(studio, /ys-world-picker|ys-world-choice/)
  assert.match(studio, /<HolographicWorldSelector/)
  assert.match(studio, /avatarRef\.current\.walkToMissionPortal\(\(\) => \{[\s\S]{0,180}setWorldPickerOpen\(true\)/)
  assert.match(studio, /zone === 'mission' && worldPickerIntentRef\.current/)
  assert.match(studio, /onClick=\{requestWorldPicker\}/)
  assert.match(hologram, /new THREE\.WebGLRenderer\(\{ alpha: true/)
  assert.match(hologram, /buildLab/)
  assert.match(hologram, /buildDome/)
  assert.match(hologram, /buildObservatory/)
  assert.match(hologram, /particleCloud/)
  assert.match(hologram, /const hoverScale = hovered \? 1\.2 : 1/)
  assert.match(hologram, /window\.setTimeout\(\(\) => selectRef\.current\(id\)/)
  assert.match(studioCss, /\.ys-world-projection__targets \{[\s\S]{0,180}direction: ltr/)
})